name: Ruby CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '* * * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: yarn --frozen--lockfile

    - name: Install rails
      run: gem install rails -v 6.0.2

    - name: Setup git
      run: (git config --global user.email "you@example.com" && git config --global user.name "Your Name")

    - name: Run tests
      run: yarn test
